### ISSUE TITLE
escript: exception error: undefined function rebar3:main/1

### ISSUE THREAD

**Issue by Linuxlovers** [vtumi/emqx_rabbitmq#1]
[root@master1 emqx_rabbitmq]# make
rebar3 compile
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [compile] Error 127

**Comment by Linuxlovers** [comment]
@vtumi 
In what directory should I compile this project?
![image](https://user-images.githubusercontent.com/23232806/77377037-f4f94200-6dac-11ea-9b65-8e32a0c423c6.png)

**Comment by Linuxlovers** [comment]
@vtumi
![image](https://user-images.githubusercontent.com/23232806/77377174-528d8e80-6dad-11ea-96af-3ad4a3b2524f.png)

**Comment by Linuxlovers** [comment]
rebar3 compile
===> Verifying dependencies...
===> Fetching cowboy (from {git,"https://github.com/emqx/cowboy",{tag,"2.7.1"}})
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/cowboy",
                                   {tag,"2.7.1"}}

**Comment by Linuxlovers** [comment]
[root@master1 emqx_rabbitmq]# make && make tests
rebar3 compile
===> Verifying dependencies...
===> Skipping cuttlefish (from {git,"https://github.com/emqx/cuttlefish",{tag,"v3.0.0"}}) as an app of the same name has already been fetched
===> Fetching gproc (from {git,"git://github.com/uwiger/gproc.git",
                 {ref,"b7b0748d7adaf9b2243921d7e9cf320690eb0544"}})
===> Failed to fetch and copy dep: {git,"git://github.com/uwiger/gproc.git",
                                  {ref,
                                      "b7b0748d7adaf9b2243921d7e9cf320690eb0544"}}
make: *** [compile] Error 1

**Comment by vtumi** [comment]
Network failure
